root: true
extends:
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true
    jsx: true
env:
  node: true
  es2018: true
  browser: true
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^_"
  no-unused-vars:
    - error
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  max-len:
    - error
    - code: 140
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
